import {
  AncovaResult,
  AnovaResult,
  ManovaResult,
  MultilevelResult,
  TTestResult,
  TTestType
} from '@/lib/types';

export const RSyntaxGenerator = {
  getTTestCode(
    type: TTestType,
    dv: string,
    groupVar?: string,
    testValue = 50,
    pairedVar2?: string,
    fileName = 'data_latihan_jasp_multilevel.csv'
  ): string {
    let script = `# ==============================================================================
# Verifikasi Uji-t (t-Test) di R
# Generated by BBKA Analytics Studio (Standar Akademik APA 7th)
# ==============================================================================

# 1. Memuat Paket
if (!requireNamespace("rstatix", quietly = TRUE)) install.packages("rstatix")
if (!requireNamespace("car", quietly = TRUE)) install.packages("car")
library(rstatix)
library(car)
library(dplyr)

# 2. Membaca Dataset
df <- read.csv("${fileName}", stringsAsFactors = TRUE)

`;

    if (type === 'independent') {
      script += `# 3. Uji Asumsi Homogenitas Varians (Levene's Test)
levene_res <- car::leveneTest(${dv} ~ as.factor(${groupVar}), data = df)
print(levene_res)

# 4. Student's t-Test (Jika Asumsi Homogenitas Terpenuhi)
ttest_student <- t.test(${dv} ~ ${groupVar}, data = df, var.equal = TRUE)
print(ttest_student)

# 5. Welch's t-Test (Jika Asumsi Homogenitas Terlanggar)
ttest_welch <- t.test(${dv} ~ ${groupVar}, data = df, var.equal = FALSE)
print(ttest_welch)

# 6. Ukuran Pengaruh (Effect Size: Cohen's d)
effect_d <- rstatix::cohens_d(df, ${dv} ~ ${groupVar}, var.equal = TRUE)
print(effect_d)

# 7. Statistik Deskriptif per Kelompok
df %>%
  group_by(${groupVar}) %>%
  summarise(
    N = n(),
    Mean = mean(${dv}, na.rm = TRUE),
    SD = sd(${dv}, na.rm = TRUE),
    SE = sd(${dv}, na.rm = TRUE) / sqrt(n()),
    Median = median(${dv}, na.rm = TRUE)
  )
`;
    } else if (type === 'paired') {
      script += `# 3. Paired Samples t-Test (Uji-t Berpasangan)
ttest_paired <- t.test(df$${dv}, df$${pairedVar2}, paired = TRUE)
print(ttest_paired)

# 4. Ukuran Pengaruh Cohen's d (Berpasangan)
diff_scores <- df$${dv} - df$${pairedVar2}
d_paired <- mean(diff_scores, na.rm = TRUE) / sd(diff_scores, na.rm = TRUE)
cat(sprintf("Cohen's d (Paired): %.4f\\n", d_paired))
`;
    } else {
      script += `# 3. One-Sample t-Test terhadap Nilai Acuan Standar (mu = ${testValue})
ttest_one <- t.test(df$${dv}, mu = ${testValue})
print(ttest_one)

# 4. Cohen's d (One-sample)
d_one <- (mean(df$${dv}, na.rm = TRUE) - ${testValue}) / sd(df$${dv}, na.rm = TRUE)
cat(sprintf("Cohen's d (One Sample): %.4f\\n", d_one))
`;
    }

    return script;
  },

  getAnovaCode(
    dv: string,
    factors: string[],
    fileName = 'data_latihan_jasp_multilevel.csv'
  ): string {
    const isTwoWay = factors.length >= 2;
    const formula = isTwoWay
      ? `${dv} ~ ${factors[0]} * ${factors[1]}`
      : `${dv} ~ ${factors[0]}`;

    return `# ==============================================================================
# Verifikasi ANOVA (Analysis of Variance) di R
# Generated by BBKA Analytics Studio (Standar Akademik APA 7th)
# ==============================================================================

# 1. Memuat Paket
if (!requireNamespace("car", quietly = TRUE)) install.packages("car")
if (!requireNamespace("effectsize", quietly = TRUE)) install.packages("effectsize")
library(car)
library(effectsize)

# 2. Membaca Dataset
df <- read.csv("${fileName}", stringsAsFactors = TRUE)

# 3. Estimasi Model ANOVA
fit_aov <- aov(${formula}, data = df)
summary(fit_aov)

# 4. ANOVA Type III Sum of Squares (Standar JASP/SPSS untuk unbalanced design)
fit_lm <- lm(${formula}, data = df)
car::Anova(fit_lm, type = "III")

# 5. Ukuran Pengaruh (Partial Eta Squared & Omega Squared)
eta_sq <- effectsize::eta_squared(fit_aov, partial = TRUE)
print(eta_sq)

# 6. Uji Lanjut Post-Hoc Tukey HSD
tukey_res <- TukeyHSD(fit_aov)
print(tukey_res)

# 7. Deskriptif Kelompok
aggregate(${dv} ~ ${factors.join(' + ')}, data = df, 
          FUN = function(x) c(N = length(x), Mean = mean(x), SD = sd(x)))
`;
  },

  getAncovaCode(
    dv: string,
    factor: string,
    covariates: string[],
    fileName = 'data_latihan_jasp_multilevel.csv'
  ): string {
    const covStr = covariates.join(' + ');

    return `# ==============================================================================
# Verifikasi ANCOVA (Analysis of Covariance) di R
# Generated by BBKA Analytics Studio (Standar Akademik APA 7th)
# ==============================================================================

# 1. Memuat Paket
if (!requireNamespace("car", quietly = TRUE)) install.packages("car")
if (!requireNamespace("emmeans", quietly = TRUE)) install.packages("emmeans")
library(car)
library(emmeans)

# 2. Membaca Dataset
df <- read.csv("${fileName}", stringsAsFactors = TRUE)

# 3. Uji Asumsi Homogenitas Gradien Regresi (Homogeneity of Slopes)
fit_homog <- lm(${dv} ~ ${factor} * (${covStr}), data = df)
summary(aov(fit_homog))

# 4. Model Utama ANCOVA (Main Effects Model)
fit_ancova <- lm(${dv} ~ ${factor} + ${covStr}, data = df)
summary(fit_ancova)

# Tabel ANCOVA Type III Sum of Squares
car::Anova(fit_ancova, type = "III")

# 5. Rata-Rata Terkoreksi (Estimated Marginal Means / Adjusted Means)
adj_means <- emmeans::emmeans(fit_ancova, ~ ${factor})
print(adj_means)

# Uji Perbandingan Pasangan Rata-Rata Terkoreksi
pairs(adj_means)
`;
  },

  getManovaCode(
    dvs: string[],
    factors: string[],
    fileName = 'data_latihan_jasp_multilevel.csv'
  ): string {
    const dvsStr = `cbind(${dvs.join(', ')})`;
    const factorStr = factors.join(' * ');

    return `# ==============================================================================
# Verifikasi MANOVA (Multivariate Analysis of Variance) di R
# Generated by BBKA Analytics Studio (Standar Akademik APA 7th)
# ==============================================================================

# 1. Memuat Paket
if (!requireNamespace("heplots", quietly = TRUE)) install.packages("heplots")
library(heplots)

# 2. Membaca Dataset
df <- read.csv("${fileName}", stringsAsFactors = TRUE)

# 3. Model MANOVA
fit_manova <- manova(${dvsStr} ~ ${factorStr}, data = df)

# 4. Statistik Uji Multivariat
cat("=== 1. Wilks' Lambda ===\\n")
summary(fit_manova, test = "Wilks")

cat("\\n=== 2. Pillai's Trace ===\\n")
summary(fit_manova, test = "Pillai")

cat("\\n=== 3. Hotelling-Lawley Trace ===\\n")
summary(fit_manova, test = "Hotelling-Lawley")

cat("\\n=== 4. Roy's Largest Root ===\\n")
summary(fit_manova, test = "Roy")

# 5. Follow-up Univariate ANOVAs
cat("\\n=== 5. Follow-up Univariate ANOVAs ===\\n")
summary.aov(fit_manova)
`;
  },

  getMultilevelCode(
    dv: string,
    clusterVar: string,
    l1Predictors: string[] = [],
    l2Predictors: string[] = [],
    fileName = 'data_latihan_jasp_multilevel.csv'
  ): string {
    const allPreds = [...l1Predictors, ...l2Predictors];
    const fixedFormula = allPreds.length > 0 ? allPreds.join(' + ') : '1';

    return `# ==============================================================================
# Verifikasi Multilevel Modeling (Linear Mixed Models / HLM) di R
# Generated by BBKA Analytics Studio (Standar Akademik APA 7th)
# Paket: lme4 & lmerTest
# ==============================================================================

# 1. Memuat Paket
if (!requireNamespace("lme4", quietly = TRUE)) install.packages("lme4")
if (!requireNamespace("lmerTest", quietly = TRUE)) install.packages("lmerTest")
if (!requireNamespace("performance", quietly = TRUE)) install.packages("performance")
library(lme4)
library(lmerTest)
library(performance)

# 2. Membaca Dataset
df <- read.csv("${fileName}", stringsAsFactors = TRUE)

# 3. Model 1: Null Model (Unconditional Model) untuk Menghitung ICC
null_model <- lmer(${dv} ~ 1 + (1 | ${clusterVar}), data = df, REML = FALSE)
summary(null_model)

# Ekstraksi Komponen Varians & ICC
var_comp <- as.data.frame(VarCorr(null_model))
tau00   <- var_comp[var_comp$grp == "${clusterVar}", "vcov"]
sigma2  <- var_comp[var_comp$grp == "Residual", "vcov"]
icc     <- tau00 / (tau00 + sigma2)

cat(sprintf("\\n--- Intraclass Correlation Coefficient (ICC) ---\\n"))
cat(sprintf("Varians Antar-Sekolah (tau00)  : %.4f\\n", tau00))
cat(sprintf("Varians Dalam-Sekolah (sigma2) : %.4f\\n", sigma2))
cat(sprintf("Nilai ICC (rho)                : %.4f (%.2f%% varians di level sekolah)\\n", icc, icc * 100))

# 4. Model 2: Random Intercept Model dengan Prediktor Siswa & Sekolah
model_2 <- lmer(${dv} ~ ${fixedFormula} + (1 | ${clusterVar}), 
                data = df, REML = FALSE)
summary(model_2)

# Evaluasi Goodness of Fit & Snijders-Bosker R2
cat("\\n--- Indeks Kecocokan Model 2 ---\\n")
cat(sprintf("AIC: %.2f | BIC: %.2f | Deviance: %.2f\\n", 
            AIC(model_2), BIC(model_2), deviance(model_2)))

# Nilai R2 Marginal & Conditional (Nakagawa / Snijders-Bosker)
performance::r2(model_2)

# 5. Ekstraksi BLUP Random Intercept Sekolah (Top 10)
school_effects <- ranef(model_2)\$${clusterVar}
head(school_effects, 10)
`;
  },

  getMiceImputationCode(
    fileName = 'data_latihan_jasp_multilevel.csv'
  ): string {
    return `# ==============================================================================
# Analisis Pola Missing Data & Imputasi Machine Learning di R
# Paket Resmi: mice (Stef van Buuren), ranger, rpart & VIM
# ==============================================================================

# 1. Memuat Paket
if (!requireNamespace("mice", quietly = TRUE)) install.packages("mice")
if (!requireNamespace("ranger", quietly = TRUE)) install.packages("ranger")
if (!requireNamespace("rpart", quietly = TRUE)) install.packages("rpart")
if (!requireNamespace("VIM", quietly = TRUE)) install.packages("VIM")
library(mice)
library(ranger)
library(rpart)
library(VIM)

# 2. Membaca Dataset
df <- read.csv("${fileName}", stringsAsFactors = TRUE)

# 3. Diagnosis Pola Missing Data (MICE Pattern Table)
cat("=== Matriks Pola Missing Data (md.pattern) ===\\n")
pattern_matrix <- mice::md.pattern(df, plot = TRUE)
print(pattern_matrix)

# 4. METODE MACHINE LEARNING 1: Random Forest Imputation (mice.impute.rf via ranger)
# Non-parametrik, menangkap interaksi multi-variabel kompleks dan non-linear
cat("\\n=== 1. Menjalankan Imputasi Machine Learning: Random Forest (ranger) ===\\n")
imp_rf <- mice::mice(df, m = 5, method = "rf", rfPackage = "ranger", seed = 500)
df_imputed_rf <- mice::complete(imp_rf, 1)
write.csv(df_imputed_rf, "data_imputed_random_forest.csv", row.names = FALSE)

# 5. METODE MACHINE LEARNING 2: Decision Trees (CART - Classification & Regression Trees)
# Berbasis recursive partitioning (rpart) tanpa asumsi linearitas
cat("\\n=== 2. Menjalankan Imputasi Machine Learning: Decision Trees (CART) ===\\n")
imp_cart <- mice::mice(df, m = 5, method = "cart", seed = 500)
df_imputed_cart <- mice::complete(imp_cart, 1)
write.csv(df_imputed_cart, "data_imputed_cart.csv", row.names = FALSE)

# 6. METODE STANDAR MICE: Predictive Mean Matching (PMM)
cat("\\n=== 3. Menjalankan Imputasi Semi-Parametrik: PMM ===\\n")
imp_pmm <- mice::mice(df, m = 5, method = "pmm", seed = 500)
df_imputed_pmm <- mice::complete(imp_pmm, 1)
write.csv(df_imputed_pmm, "data_imputed_pmm.csv", row.names = FALSE)

cat("\\n✓ Selesai! Dataset hasil imputasi Machine Learning tersimpan siap dianalisis.\\n")
`;
  },

  getMergeDataCode(
    primaryFileName: string,
    secondaryFileName: string,
    primaryKey: string,
    secondaryKey: string,
    joinType: 'left' | 'inner' = 'left',
    secondaryColsToMerge: string[] = [],
    sheetName?: string
  ): string {
    const isExcel = (secondaryFileName || '').endsWith('.xlsx') || (secondaryFileName || '').endsWith('.xls');
    const isSameKey = primaryKey === secondaryKey;
    const byClause = isSameKey ? `by = "${primaryKey}"` : `by = c("${primaryKey}" = "${secondaryKey}")`;
    const joinFunc = joinType === 'inner' ? 'inner_join' : 'left_join';
    const colsToAggregate = secondaryColsToMerge.filter(c => c !== secondaryKey);
    const colsSelectStr = colsToAggregate.length > 0
      ? `c("${secondaryKey}", ${colsToAggregate.map(c => `"${c}"`).join(', ')})`
      : 'everything()';

    return `# ==============================================================================
# Script Penggabungan Data Multi-Level (Merge Siswa Level 1 & Guru Level 2) di R
# Generated by BBKA Analytics Studio (Standar Tidyverse R)
# ==============================================================================

# 1. Memuat Paket yang Diperlukan
if (!requireNamespace("dplyr", quietly = TRUE)) install.packages("dplyr")
if (!requireNamespace("readr", quietly = TRUE)) install.packages("readr")
${isExcel ? 'if (!requireNamespace("readxl", quietly = TRUE)) install.packages("readxl")\n' : ''}library(dplyr)
library(readr)
${isExcel ? 'library(readxl)\n' : ''}
# 2. Membaca Dataset Utama (Data Siswa / Level 1)
df_siswa <- read_csv("${primaryFileName || 'data_siswa_an.csv'}")

# 3. Membaca Dataset Sekunder (Data Guru / Satuan Pendidikan Level 2)
${isExcel
  ? `df_guru_raw <- read_excel("${secondaryFileName || 'data_guru_sulingjar.xlsx'}"${sheetName ? `, sheet = "${sheetName}"` : ''})`
  : `df_guru_raw <- read_csv("${secondaryFileName || 'data_guru_sulingjar.csv'}")`
}

# 4. Agregasi Rata-Rata Data Guru per Satuan Pendidikan (${secondaryKey})
# Jika 1 sekolah memiliki beberapa guru responden, nilai numerik diagregasikan ke rata-rata sekolah
df_guru_agg <- df_guru_raw %>%
  select(${colsSelectStr}) %>%
  group_by(${secondaryKey}) %>%
  summarise(across(where(is.numeric), ~ mean(.x, na.rm = TRUE)), .groups = "drop")

# 5. Eksekusi Penggabungan Relasional (${joinFunc.toUpperCase()})
df_merged <- df_siswa %>%
  ${joinFunc}(df_guru_agg, ${byClause})

# 6. Ringkasan Diagnostik Hasil Penggabungan
cat("==============================================================================\\n")
cat("DIAGNOSTIK HASIL MERGE DATA MULTI-LEVEL:\\n")
cat(sprintf("  - Total Baris Awal (Siswa)       : %d baris\\n", nrow(df_siswa)))
cat(sprintf("  - Total Baris Akhir (Merged)     : %d baris\\n", nrow(df_merged)))
cat(sprintf("  - Total Kolom Bertambah          : %d variabel baru\\n", ncol(df_merged) - ncol(df_siswa)))
cat("==============================================================================\\n")

glimpse(df_merged)

# 7. Menyimpan Dataset Gabungan Siap Analisis HLM / Regresi
write_csv(df_merged, "data_merged_siswa_guru_clean.csv")
cat("\\n✓ File 'data_merged_siswa_guru_clean.csv' berhasil disimpan dan siap diverifikasi!\\n")
`;
  },

  getDataPrepCode(
    subsetCols: string[],
    filterRules: Array<{ col: string; op: string; val: string }> | string = [],
    fileName = 'data_asesmen_nasional_clean.csv',
    mergeInfo?: {
      isMerged: boolean;
      secondaryFileName?: string;
      primaryKey?: string;
      secondaryKey?: string;
      joinType?: 'left' | 'inner';
      secondaryCols?: string[];
      sheetName?: string;
    }
  ): string {
    const colsStr = subsetCols.length > 0 ? subsetCols.map(c => `"${c}"`).join(', ') : '';

    let filterRCode = '';
    if (Array.isArray(filterRules) && filterRules.length > 0) {
      const conditions = filterRules.map(r => {
        if (r.op === '==') return `${r.col} == "${r.val}"`;
        if (r.op === '!=') return `${r.col} != "${r.val}"`;
        if (r.op === '>') return `${r.col} > ${r.val}`;
        if (r.op === '>=') return `${r.col} >= ${r.val}`;
        if (r.op === '<') return `${r.col} < ${r.val}`;
        if (r.op === '<=') return `${r.col} <= ${r.val}`;
        if (r.op === 'contains') return `grepl("${r.val}", as.character(${r.col}), ignore.case = TRUE)`;
        if (r.op === 'not_null') return `!is.na(${r.col})`;
        return `${r.col} ${r.op} ${r.val}`;
      }).join(' &\n    ');
      filterRCode = `\n  # Filter Observasi Baris\n  filter(\n    ${conditions}\n  ) %>%`;
    }

    let mergeBlock = '';
    if (mergeInfo && mergeInfo.isMerged && mergeInfo.secondaryFileName) {
      const isExcel = mergeInfo.secondaryFileName.endsWith('.xlsx') || mergeInfo.secondaryFileName.endsWith('.xls');
      const pKey = mergeInfo.primaryKey || 'kd_sekolah';
      const sKey = mergeInfo.secondaryKey || 'kd_sekolah';
      const byClause = pKey === sKey ? `by = "${pKey}"` : `by = c("${pKey}" = "${sKey}")`;
      const joinFn = mergeInfo.joinType === 'inner' ? 'inner_join' : 'left_join';

      mergeBlock = `
# ------------------------------------------------------------------------------
# 2b. Penggabungan Data Sekunder (Data Guru / Satuan Pendidikan Level 2)
# ------------------------------------------------------------------------------
${isExcel ? `df_guru_raw <- readxl::read_excel("${mergeInfo.secondaryFileName}"${mergeInfo.sheetName ? `, sheet = "${mergeInfo.sheetName}"` : ''})` : `df_guru_raw <- read_csv("${mergeInfo.secondaryFileName}")`}

df_guru_agg <- df_guru_raw %>%
  group_by(${sKey}) %>%
  summarise(across(where(is.numeric), ~ mean(.x, na.rm = TRUE)), .groups = "drop")

df <- df %>%
  ${joinFn}(df_guru_agg, ${byClause})
`;
    }

    return `# ==============================================================================
# Script Persiapan & Pemrosesan Data Lanjutan di R (Data Wrangling Script)
# Generated by BBKA Analytics Studio (Standar Tidyverse R)
# ==============================================================================

# 1. Memuat Paket yang Diperlukan
if (!requireNamespace("dplyr", quietly = TRUE)) install.packages("dplyr")
if (!requireNamespace("readr", quietly = TRUE)) install.packages("readr")
library(dplyr)
library(readr)

# 2. Membaca Dataset Utama
df <- read_csv("${fileName}")
${mergeBlock}
# 3. Tinjauan Struktur Data Awal
glimpse(df)

# 4. Pemrosesan Data (Filter & Subsetting Kolom)
df_clean <- df %>%${filterRCode}
  dplyr::select(${colsStr || 'everything()'})

# 5. Ringkasan Deskriptif Data Bersih
cat("=== Ringkasan Deskriptif Data Bersih ===\\n")
summary(df_clean)

# 6. Menyimpan Hasil Pembersihan Data
write_csv(df_clean, "data_clean_ready.csv")
cat("\\n✓ Data bersih berhasil disimpan ke 'data_clean_ready.csv'!\\n")
`;
  },

  getRegressionCode(
    dv: string,
    blocks: { blockNumber: number; blockName?: string; variables: string[] }[],
    fileName = 'data_asesmen_nasional.csv'
  ): string {
    let script = `# ==============================================================================
# Regresi Linier Berganda Berjenjang (Hierarchical Linear Regression) di R
# Estimasi Bertingkat (R² Change, Standardized Beta, VIF)
# Generated by BBKA Analytics Studio (Standar Akademik APA 7th)
# ==============================================================================

# 1. Memuat Paket
if (!requireNamespace("car", quietly = TRUE)) install.packages("car")
if (!requireNamespace("lm.beta", quietly = TRUE)) install.packages("lm.beta")
library(car)
library(lm.beta)

# 2. Membaca Dataset
df <- read.csv("${fileName}", stringsAsFactors = TRUE)

`;

    let cumVars: string[] = [];
    const modelVars: string[] = [];

    blocks.forEach((b, idx) => {
      cumVars = Array.from(new Set([...cumVars, ...b.variables]));
      const mName = `model_${idx + 1}`;
      modelVars.push(mName);
      script += `# Model ${idx + 1}: ${b.blockName || `Blok ${idx + 1}`}
${mName} <- lm(${dv} ~ ${cumVars.join(' + ')}, data = df)
summary(${mName})
summary(lm.beta(${mName})) # Standardized Beta Coefficients
`;
      if (cumVars.length > 1) {
        script += `car::vif(${mName}) # Multicollinearity Check (VIF)\n\n`;
      } else {
        script += `\n`;
      }
    });

    if (modelVars.length > 1) {
      script += `# ==============================================================================
# 3. Uji Perbandingan Model Berjenjang (Hierarchical Model Comparison / F-Change)
# ==============================================================================
anova_comp <- anova(${modelVars.join(', ')})
print(anova_comp)
`;
    }

    return script;
  },

  getSEMCode(
    syntax: string,
    fileName = 'data_asesmen_nasional.csv'
  ): string {
    return `# ==============================================================================
# Structural Equation Modeling (SEM) & Path Analysis di R
# Package: lavaan (Latent Variable Analysis)
# Generated by BBKA Analytics Studio (Standar Akademik APA 7th)
# ==============================================================================

# 1. Memuat Paket
if (!requireNamespace("lavaan", quietly = TRUE)) install.packages("lavaan")
if (!requireNamespace("semPlot", quietly = TRUE)) install.packages("semPlot")
library(lavaan)
library(semPlot)

# 2. Membaca Dataset
df <- read.csv("${fileName}", stringsAsFactors = TRUE)

# 3. Spesifikasi Model Sintaks Lavaan
model_syntax <- '
${syntax.trim()}
'

# 4. Estimasi Model SEM
fit <- sem(model = model_syntax, data = df, missing = "fiml", estimator = "ML", fixed.x = FALSE)
summary(fit, fit.measures = TRUE, standardized = TRUE, rsquare = TRUE)

# 5. Ekstraksi Fit Indices Utama
fitMeasures(fit, c("chisq", "df", "pvalue", "cfi", "tli", "rmsea", "rmsea.ci.lower", "rmsea.ci.upper", "srmr", "aic", "bic"))

# 6. Parameter Estimates & Efek Mediasi
parameterEstimates(fit, standardized = TRUE, ci = TRUE)

# 7. Visualisasi Diagram Jalur (Path Diagram)
semPaths(fit, what = "std", edge.label.cex = 0.9, layout = "tree", style = "ram", nCharNodes = 0)
`;
  },

  getIPDMetaCode(
    dv: string,
    focalPredictor: string,
    clusterVar: string,
    covariates: string[] = [],
    fileName = 'data_asesmen_nasional.csv'
  ): string {
    const covStr = covariates.length > 0 ? ` + ${covariates.join(' + ')}` : '';
    const formulaStr = `${dv} ~ ${focalPredictor}${covStr}`;

    return `# ==============================================================================
# Two-Stage Individual Participant Data (IPD) Meta-Analysis di R
# Standard: Brunner et al. (2022) & Eryilmaz & Strietholt (2025)
# Generated by BBKA Analytics Studio (Standar Publikasi Jurnal Q1)
# ==============================================================================

# 1. Memuat Paket
if (!requireNamespace("metafor", quietly = TRUE)) install.packages("metafor")
if (!requireNamespace("dplyr", quietly = TRUE)) install.packages("dplyr")
if (!requireNamespace("ggplot2", quietly = TRUE)) install.packages("ggplot2")
library(metafor)
library(dplyr)
library(ggplot2)

# 2. Membaca Dataset
df <- read.csv("${fileName}", stringsAsFactors = TRUE)

# 3. TAHAP 1: Estimasi Regresi OLS Terpisah per Klaster/Provinsi (${clusterVar})
cluster_results <- df %>%
  group_by(${clusterVar}) %>%
  filter(n() >= ${covariates.length + 5}) %>%
  do({
    fit <- lm(${formulaStr}, data = .)
    s <- summary(fit)
    coefs <- coef(s)
    
    if ("${focalPredictor}" %in% rownames(coefs)) {
      data.frame(
        cluster_id = unique(.[[ "${clusterVar}" ]]),
        n_obs      = nrow(.),
        beta       = coefs["${focalPredictor}", "Estimate"],
        se         = coefs["${focalPredictor}", "Std. Error"],
        t_val      = coefs["${focalPredictor}", "t value"],
        p_val      = coefs["${focalPredictor}", "Pr(>|t|)"]
      )
    } else {
      data.frame()
    }
  }) %>%
  ungroup()

cat("=== Ringkasan Estimasi Tahap 1 per Klaster (${clusterVar}) ===\\n")
print(cluster_results)

# 4. TAHAP 2: Random-Effects Meta-Analysis via REML (Restricted Maximum Likelihood)
meta_fit <- rma(
  yi = beta, 
  sei = se, 
  data = cluster_results, 
  method = "REML",
  slab = cluster_results$cluster_id
)

cat("\\n=== Ringkasan Model Meta-Analisis IPD (Tahap 2) ===\\n")
summary(meta_fit)

# 5. Visualisasi Forest Plot Standar Publikasi Internasional
forest(
  meta_fit,
  xlab = "Koefisien Efek (${focalPredictor} -> ${dv})",
  slab = cluster_results$cluster_id,
  showweights = TRUE,
  col = "#008080",
  border = "#004d4d",
  header = c("Klaster / Wilayah", "Estimasi [95% CI] (Bobot %)")
)

# 6. Diagnostik Heterogenitas & Uji Publikasi
cat("\\n--- Metrik Heterogenitas ---\\n")
cat(sprintf("I-squared (I^2) : %.2f%%\\n", meta_fit$I2))
cat(sprintf("Tau-squared (tau^2) : %.4f\\n", meta_fit$tau2))
cat(sprintf("Cochran Q Test  : Q = %.2f (df = %d, p = %.5f)\\n", meta_fit$QE, meta_fit$k - 1, meta_fit$QEp))
`;
  }
};
